[tool.poetry]
name = "python-library"
version = "1.0.3"
description = "Provide base template for python library"
authors = ["JaeyoungHeo <jay.jaeyoung@gmail.com>"]
maintainers = ["JaeyoungHeo <jay.jaeyoung@gmail.com>"]
readme = "README.md"
repository = "https://github.com/8percent/python-library"
license = "MIT"
packages = [
    { include = "python_library", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9 <3.11"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
isort = "^5.12.0"
tox = "^4.11.4"
flake8 = "^6.1.0"
pytest-cov = "^4.0.0"
codecov = "^2.1.12"
black = "^23.11.0"
pre-commit = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Lint Configurations
[tool.isort]
force_single_line = "True"
profile = "black"
line_length = "79"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.black]
preview = "True"
line-length = "79"
target-version = ['py310']
skip-string-normalization = "True"

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
testpaths = [
    "tests",
]
