[tool.poetry]
name = "python-library"
version = "1.0.4"
description = "Provide base template for python library"
authors = ["JaeyoungHeo <jay.jaeyoung@gmail.com>"]
maintainers = ["JaeyoungHeo <jay.jaeyoung@gmail.com>"]
readme = "README.md"
repository = "https://github.com/8percent/python-library"
license = "MIT"
packages = [
    { include = "python_library", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9 <3.12"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
isort = "^5.10.1"
tox = "^4.3.5"
flake8 = "^6.0.0"
pytest-cov = "^4.0.0"
codecov = "^2.1.12"
black = "^22.6.0"
pre-commit = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Lint Configurations
[tool.isort]
profile = "black"

[tool.black]
preview = true
target-version = ['py39', 'py310', 'py311']

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
testpaths = [
    "tests",
]
